version: '4.26'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - luizgpolido_data:/var/lib/mysql


volumes:
      luizgpolido_data: